-keep class com.bun.miitmdid.core.** {*;}
-keep class com.bun.** {*;}
-keep class com.asus.** {*;}
-keep class com.zui.** {*;}
-keep class com.huawei.** {*;}
-keep class com.samsung.** {*;}
-keep class com.netease.** {*;}